field: 10ee67f6-a896-435c-b04c-b67b74c0765b # Accordion
fieldLayouts:
  df741d4d-9752-4fcf-9fe8-d326e11498ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e81c5188-56d1-401d-9d2f-ec4f23767c40 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e61dda14-d733-43f7-8745-cffd2bdcd76d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aad62203-c66e-4093-9348-41aa766ed9a7 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1576a7a3-cfd6-41a1-b77d-99984ee5735c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c635e61-d12f-4360-939a-3ecb136dd387
        userCondition: null
fields:
  aad62203-c66e-4093-9348-41aa766ed9a7: # Content
    columnSuffix: snjncvsx
    contentColumnType: text
    fieldGroup: null
    handle: mainContent
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e81c5188-56d1-401d-9d2f-ec4f23767c40: # Heading
    columnSuffix: umyuxmig
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: accordion
name: Accordion
sortOrder: 1
