field: 746551af-25b1-44fe-9664-5b486f338e8f # Resources
fieldLayouts:
  1129884e-6684-4e12-b177-aed916a04677:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8209fa7a-c8a9-49db-9722-dc8d3ca60e1b # Related Topic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 005f39cb-b9fc-4397-882b-1bae5b4f16e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f0380ce6-9968-4ff1-91c9-2b3d30f3e128 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73cb13f7-ab86-4554-923d-cd3dc5dae780
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 934ff820-0a5c-44dd-84e6-ad7479cf1669 # Grades
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc9a9437-70d5-4121-a51b-17a4865eb905
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 551cc461-899a-4f67-a476-944bb317e130
        userCondition: null
fields:
  934ff820-0a5c-44dd-84e6-ad7479cf1669: # Grades
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: grades
    instructions: null
    name: Grades
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:aaf07435-c887-4c52-adec-c8e396f45121' # Grades
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8209fa7a-c8a9-49db-9722-dc8d3ca60e1b: # Related Topic
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: relatedTopic
    instructions: null
    name: 'Related Topic'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:5190fe78-2768-4f43-9d82-2c1689063874' # Topic
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  f0380ce6-9968-4ff1-91c9-2b3d30f3e128: # Description
    columnSuffix: mlxfvihe
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: overview
name: Overview
sortOrder: 2
