fieldLayouts:
  48e21b64-a70b-4c55-b60e-e3514391eed9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c1a3153-df84-496e-9115-75b576d30b84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c77329d-d4fe-4a8d-a1c3-9fb8d8556b18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b29dd9b-d348-49fb-8574-a19d761cbdf0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2325607c-3db2-4c1a-a15f-267b0024ea84 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c42c259a-2148-4d2f-92e8-69d727405fd5
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: ce6b3aac-2f90-4847-a951-755d1ed0f7fd
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b9cae8c2-183e-482d-b1d2-9bb60fb47ef5 # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
