fieldLayouts:
  6ae20159-6087-451e-80cf-06bb9d29515b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 642e95e8-6f0a-40a8-a6a1-48741c5fa94b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: 'Unit Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81f9ca77-f93f-4dd8-813d-c79016fc51e9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 97f20e91-e7a7-4cf8-8687-620fc3718308 # Icon
            instructions: 'Used when this entry is rendered dynamically on other pages through the builder "Entries" component.'
            label: 'Unit Icon'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45b26ee3-fdac-41f4-ada9-45c1752e5422
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f01ad19-64d3-45a2-be5f-7a1faccb83f5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20e7c489-7e26-4225-a556-69479c0af1d6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2325607c-3db2-4c1a-a15f-267b0024ea84 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e569fb1-2994-4d7e-9194-fffbf07eeb37
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 12573966-8c7c-4e41-85a1-c4fc66c47018
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5190fe78-2768-4f43-9d82-2c1689063874 # Topic
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
