baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Finding Flow Solutions'
primary: true
siteGroup: 3376bd1e-aac9-440e-90c4-07724ae7b4b3 # Finding Flow Solutions
sortOrder: 1
