childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  a1b3e059-425f-4bed-99a4-8793755fb05c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 10ee67f6-a896-435c-b04c-b67b74c0765b # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8374abf0-26c8-48f3-9836-6627f0a5c920
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 7c75adde-ad78-460b-81cc-53d9b8198afa
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: accordion
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Accordion
sortOrder: 5
topLevel: true
