childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  2b071daf-1728-4192-b808-81278a46b461:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1806d0d-7979-404c-8408-fd49a948d2e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d957729c-ed9b-4612-950c-2ffee4ee78cb # Drip Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 272e521a-db41-4585-837a-0eeceab0d036
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 9d63640b-33b3-498e-844c-31e5cd2c305d
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: drip
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Drip
sortOrder: 11
topLevel: true
