childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  fffe29eb-0d5a-4b0f-867b-1d9aac63de24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a631efac-d9d3-4707-b710-3fddf818b6ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 558e47cd-6550-45f3-ba3f-db92c941f557 # Display Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b807a372-e49a-44e4-a03a-14a5321cf2e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4969a3f3-fa47-4402-a0a8-35e34304b566 # Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35ab905d-8b27-47ca-b740-98a264ef23f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89433a62-b1d3-4515-b51c-a2b9be66570a # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d7adaf-9c30-4182-9d6d-af1d53f1a8da
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: af7e71b0-2fe9-4f59-a1ae-952d50f1294b # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb1f594e-11ca-4c41-8e8b-e8d40471cff4
            userCondition: null
            warning: null
            width: 50
        name: Default
        uid: dabb3468-647d-4cbb-a800-3cbd91de4355
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: entries
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Entries
sortOrder: 12
topLevel: true
