childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  9e4ca2be-a78e-4b2f-921a-b30f6a6abc0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 97f20e91-e7a7-4cf8-8687-620fc3718308 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f03208ad-5b05-48b3-ad1a-306742d6519e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a5d1398-dd06-4d75-9923-3719b271707e # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59f91383-6089-4688-b980-38003502616c
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 6e07d985-aa2d-47ed-ad73-ac1f8a3e23a7
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: icon
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Icon
sortOrder: 12
topLevel: false
