childBlocks:
  - navigationItem
conditions: null
description: ''
enabled: true
field: 4790034a-9974-43d3-b42d-f91993136fec # Navigation
fieldLayouts:
  ae1f1efc-f791-4393-878b-540dcd5a8677:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 89433a62-b1d3-4515-b51c-a2b9be66570a # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5565e7d-ef53-47d5-bb5e-2db728fff27e
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: d330e368-52cb-48b2-8ef5-a4542e09379d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: navigationList
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Navigation List'
sortOrder: 2
topLevel: true
