childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  d73d021e-013e-4ace-921f-6aa00da4f6ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 97f20e91-e7a7-4cf8-8687-620fc3718308 # Icon
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 260dfeee-396e-4a50-9037-208f38bbea17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94a6ce36-1be5-4808-a14e-a6bc9ad7dbe8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af7e71b0-2fe9-4f59-a1ae-952d50f1294b # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64694427-664e-4d1b-a554-4cd4c8b6795d
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 1ab02493-b99c-48c3-b90a-52f23faae781
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: product
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Product
sortOrder: 17
topLevel: false
