childBlocks:
  - product
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  e929a2ef-e49f-4032-8ea7-9a4d8f9cc631:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3a20b368-94ec-4d50-8821-e726cfdc8b18 # Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2194d5a0-2b82-435f-9990-5cd09dc01327
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19d2a1ca-072b-4ea1-9a91-7bbd6e017807
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89433a62-b1d3-4515-b51c-a2b9be66570a # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b96406af-44a0-46d8-a234-a2fff12f36cf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: af7e71b0-2fe9-4f59-a1ae-952d50f1294b # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a23887c9-41d3-474c-91c8-8ec560f4e409
            userCondition: null
            warning: null
            width: 50
        name: Default
        uid: 88d7aa50-fcc1-4ce6-a25d-c1880bbc1c16
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: products
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Products
sortOrder: 16
topLevel: true
