childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  61c33d95-6803-4868-a09c-766aa19baca2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7eb7054b-0c88-4f0a-8419-ec23f9d3e3b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ce0d32ea-55b7-4338-9f10-b8f8f658fe80 # Toggle
            instructions: null
            label: 'Disable Filter'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9442c316-079a-4677-bc72-3c7628e2cdb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 746551af-25b1-44fe-9664-5b486f338e8f # Resources
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38ab2eff-81ae-44ef-821f-2d6066373d7e
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: c3c7dc9d-0352-4698-8293-6726d16cc58d
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: resources
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Resources
sortOrder: 18
topLevel: true
