childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  9b09b164-2e00-41aa-b969-dbc72d158b81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5a5d1398-dd06-4d75-9923-3719b271707e # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6bec5de-8416-484d-b553-9fab3411c315
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de1e2409-6942-48af-b94b-7b007ad6d101 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 104fe245-dcb1-4dd6-875f-043018a8cd0d
            userCondition: null
            warning: null
            width: 100
        name: Default
        uid: 36357d4b-4414-48b7-a5cd-25c52626c044
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: slider
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Slider
sortOrder: 20
topLevel: true
