childBlocks: null
conditions: null
description: ''
enabled: true
field: 2d58a77a-5f3a-4a5a-bb66-9716f5433ca8 # Builder
fieldLayouts:
  9072f276-070c-4f12-ac10-53f74496c042:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3a20b368-94ec-4d50-8821-e726cfdc8b18 # Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 677c0b9b-615a-401f-bd6c-0ec0acef1ef1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 64f82816-9c12-49e0-9e11-5cd9d3bfbaa1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6a0d1b5-3a6d-41f0-9d9a-eb3be01faa19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a5d1398-dd06-4d75-9923-3719b271707e # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b01f0cf5-90b2-49bc-ad41-a97cc55dc2e8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e43cc6fc-55ea-4e8e-9416-5c305c03eff6 # Content (Secondary)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a60a2665-f50c-4991-a7f5-369fe58c546a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 89433a62-b1d3-4515-b51c-a2b9be66570a # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8a8b4d0-625a-4454-99e7-a10a8a4fbcfe
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: af7e71b0-2fe9-4f59-a1ae-952d50f1294b # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59b180b4-0d1c-4160-ac1c-79336569f1c0
            userCondition: null
            warning: null
            width: 50
        name: Default
        uid: 48daf023-b42d-463f-8ed2-fe67b78bf413
        userCondition: null
group: 0e1b3603-b225-4550-ae51-552c4aefdcc2 # Components
groupChildBlockTypes: true
handle: text
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 24
topLevel: true
