columnSuffix: null
contentColumnType: string
fieldGroup: c6e47093-5583-4acc-b6e6-9acfda9c212b # Common
handle: accordion
instructions: null
name: Accordion
searchable: false
settings:
  contentTable: '{{%matrixcontent_accordion}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
