columnSuffix: hykwqtea
contentColumnType: string
fieldGroup: c6e47093-5583-4acc-b6e6-9acfda9c212b # Common
handle: dripForm
instructions: null
name: 'Drip Form'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Elementary
        -
          - value
          - elementary
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Middle School'
        -
          - value
          - middleSchool
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
