columnSuffix: null
contentColumnType: string
fieldGroup: c6e47093-5583-4acc-b6e6-9acfda9c212b # Common
handle: navigation
instructions: null
name: Navigation
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
