defaultPlacement: end
enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  151384ef-d890-48a6-afc0-ec0b64beb573: # Finding Flow Solutions
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
