defaultPlacement: end
enableVersioning: true
handle: faqIndex
name: 'FAQ Index'
propagationMethod: all
siteSettings:
  151384ef-d890-48a6-afc0-ec0b64beb573: # Finding Flow Solutions
    enabledByDefault: true
    hasUrls: true
    template: layouts/_faq.twig
    uriFormat: faq
type: single
