defaultPlacement: end
enableVersioning: true
handle: purchasing
name: Purchasing
propagationMethod: all
siteSettings:
  151384ef-d890-48a6-afc0-ec0b64beb573: # Finding Flow Solutions
    enabledByDefault: true
    hasUrls: true
    template: layouts/_builder.twig
    uriFormat: 'purchasing/{slug}'
structure:
  maxLevels: null
  uid: 0bdb60e3-7bd3-4292-a190-6dfe59346f1f
type: structure
