defaultPlacement: end
enableVersioning: true
handle: topic
name: Topic
propagationMethod: all
siteSettings:
  151384ef-d890-48a6-afc0-ec0b64beb573: # Finding Flow Solutions
    enabledByDefault: true
    hasUrls: true
    template: layouts/_builder.twig
    uriFormat: 'topic/{slug}'
structure:
  maxLevels: null
  uid: 8e9ebbf4-917f-4349-b3c8-17bdea898691
type: structure
